version: "3.5"

services:
  db:
    container_name: db
    image: mysql:5.6
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: helpdesk
      MYSQL_USER: adriano
      MYSQL_PASSWORD: adriano
